#include "..\..\General\_Includes.h"

#define THRASHIT3D_DEFAULT_FOCAL			200
#define THRASHIT3D_DEFAULT_TRIANGLE_COUNT	1000

#define THRASHIT3D_DEFAULT_VIEWER_Z			-200	



#define THRASHIT3D_RENDER_WIREFRAME	0
#define THRASHIT3D_RENDER_FLAT		1
#define THRASHIT3D_RENDER_GOURAUD	2
#define THRASHIT3D_RENDER_NONE		3

#define THRASHIT3D_RENDER_DEFAULT	THRASHIT3D_RENDER_FLAT

#define THRASHIT3D_VERMAJOR			"0."
#define THRASHIT3D_VERMINOR			"1."
#define THRASHIT3D_VERSTATE			"alpha"		
#define THRASHIT3D_VERBUILD			"3"			

//undefine these to disable log file
//#ifdef _DEBUG
	#define THRASHIT3D_LOGFILE
	#include "..\..\General\File\Logfile.h"
	#include "..\..\General\File\PerformanceLogger.h"
//#endif

#ifdef _DEBUG
	#define THRASHIT3D_COUNTZOVERDRAW
#endif

//undefine these to disable math lookup tables 
//#define THRASHIT3D_LOOKUPTABLES




#define THRASHIT3D_PI					3.1415927f
#define THRASHIT3D_2PI					(2.0f * THRASHIT3D_PI)
#define THRASHIT3D_2PIRAD				THRASHIT3D_2PI
#define THRASHIT3D_PIRAD				THRASHIT3D_PI
#define THRASHIT3D_2PIDEG				360.0f
#define THRASHIT3D_PIDEG				180.0f
#define	THRASHIT3D_PIOVER180			((THRASHIT3D_PI) / THRASHIT3D_PIDEG)
#define	THRASHIT3D_DEGTORAD(DEG)		((FLOAT) DEG * THRASHIT3D_PIOVER180)

#define THRASHIT3D_LOOKUPRESOLUTION		100.0f
#define THRASHIT3D_LOOKUPTABLESIZE		((int) (4.0f * THRASHIT3D_LOOKUPRESOLUTION * THRASHIT3D_PI) ) + 1
#define THRASHIT3D_LOOKUPTABLEOFFSET	(int) (2.0f * THRASHIT3D_LOOKUPRESOLUTION * THRASHIT3D_PI)


#define THRASHIT3D_TIANGLERESOLUTION	8192.0f //2pow13,	must be multiple of 2			
#define THRASHIT3D_2PITI				THRASHIT3D_TIANGLERESOLUTION 
#define THRASHIT3D_PITI					THRASHIT3D_TIANGLERESOLUTION / 2.0f
#define THRASHIT3D_PIOVER2TI			THRASHIT3D_TIANGLERESOLUTION / 4.0f
#define THRASHIT3D_TIANGLEOVERDEG		(THRASHIT3D_TIANGLERESOLUTION / THRASHIT3D_2PI)
#define THRASHIT3D_TIANGLEOVERRAD		(THRASHIT3D_TIANGLERESOLUTION / THRASHIT3D_2PI)
#define THRASHIT3D_DEGOVERTIANGLE		(THRASHIT3D_2PI / THRASHIT3D_TIANGLERESOLUTION)
#define THRASHIT3D_RADOVERTIANGLE		(THRASHIT3D_2PI / THRASHIT3D_TIANGLERESOLUTION)

#define	THRASHIT3D_DEGTOTIANGLE(DEG)	(int) ((FLOAT) DEG * THRASHIT3D_TIANGLEOVERDEG)
#define	THRASHIT3D_RADTOTIANGLE(RAD)	(int) ((FLOAT) RAD * THRASHIT3D_TIANGLEOVERRAD)
#define	THRASHIT3D_TIANGLETODEG(TI)		((FLOAT) TI * THRASHIT3D_DEGOVERTIANGLE)
#define	THRASHIT3D_TIANGLETORAD(TI)		((FLOAT) TI * THRASHIT3D_RADOVERTIANGLE)